services:
  server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.armv8
    volumes:
      - ./.env:/app/.env
      - ./config.yml:/app/config.yml
#      - ./state.yml:/app/state.yml